# Generated by Django 4.2.6 on 2023-10-13 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Beer',
            fields=[
                ('name', models.CharField(max_length=50, verbose_name='Наименование')),
                ('identification_number', models.AutoField(primary_key=True, serialize=False, verbose_name='Идентификационный номер')),
                ('unit_of_measure', models.CharField(default='литр', max_length=10, verbose_name='Единица измерения')),
                ('quantity', models.IntegerField(default=1, verbose_name='Количество')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('status', models.CharField(choices=[('Норма', 'Норма'), ('Брак', 'Брак'), ('Просроченный', 'Просроченный')], default='Норма', max_length=20)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beers.category', verbose_name='Категория')),
            ],
        ),
    ]
